{{- $component := "loki" }}
{{- if .Values.loki.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gophprofile.componentName" (dict "context" . "component" $component) }}
  labels:
    {{- include "gophprofile.componentLabels" (dict "context" . "component" $component) | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: 3100
      targetPort: http
    - name: grpc
      port: 9096
      targetPort: grpc
  selector:
    {{- include "gophprofile.componentSelectorLabels" (dict "context" . "component" $component) | nindent 4 }}
{{- end }}
