{{- $component := "minio" }}
{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gophprofile.componentName" (dict "context" . "component" $component) }}
  labels:
    {{- include "gophprofile.componentLabels" (dict "context" . "component" $component) | nindent 4 }}
spec:
  ports:
    - name: api
      port: 9000
      targetPort: api
    - name: console
      port: 9001
      targetPort: console
  selector:
    {{- include "gophprofile.componentSelectorLabels" (dict "context" . "component" $component) | nindent 4 }}
{{- end }}
