apiVersion: v1
kind: ConfigMap
metadata:
  name: gophprofile
data:
  HTTP_ADDR: ":8080"
  PUBLIC_BASE_URL: http://gophprofile.local
  S3_BUCKET: avatars
  S3_USE_SSL: "false"
  KAFKA_BROKERS: kafka:9092
  KAFKA_GROUP: gophprofile-worker
